version: 2
jobs:
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "run my tests!"
      - persist_to_workspace:
          root: .
          paths:
            - locale
            - .tx
  transifex:
    docker:
      - image: python:2.7
    steps:
      - attach_workspace:
          at: txci
      - run: pip install transifex-client
      - run: cd txci && tx push --source -l en --no-interactive
workflows:
  version: 2
  my-ci-flow:
    jobs:
      - test
      - transifex:
          requires:
            - test
          filters:
            branches:
              only:
                - master
